import { ThemeConfig, PresetMode, SavedCustomTheme } from "@/types/theme";

export const DEFAULT_THEME_CONFIG: ThemeConfig = {
  preset: "auto",
  background: "dark",
  primaryAccent: "blue",
  aiCoreColor: "cyan",
  agentGlow: "global",
  glassIntensity: "balanced",
  borderIntensity: "standard",
  motion: "cinematic",
  backgroundEffect: "particles",
  density: "comfortable",
  timeAwareAuto: true,
};

export const THEME_PRESETS: Record<PresetMode, {
  name: string;
  tagline: string;
  description: string;
  badge: string;
  config: ThemeConfig;
  previewColors: { bg: string; surface: string; accent: string; aiCore: string };
}> = {
  auto: {
    name: "Auto Adaptive",
    tagline: "System & Time Aware",
    description: "Follows system theme and automatically adapts lighting based on local time.",
    badge: "Smart",
    config: {
      preset: "auto",
      background: "dark",
      primaryAccent: "blue",
      aiCoreColor: "cyan",
      agentGlow: "global",
      glassIntensity: "balanced",
      borderIntensity: "standard",
      motion: "cinematic",
      backgroundEffect: "particles",
      density: "comfortable",
      timeAwareAuto: true,
    },
    previewColors: { bg: "#05070B", surface: "#111318", accent: "#2E7BFF", aiCore: "#38BDF8" },
  },
  obsidian: {
    name: "Obsidian",
    tagline: "Signature AI Look",
    description: "Deep black background, electric blue accents, and high-contrast telemetry.",
    badge: "Signature",
    config: {
      preset: "obsidian",
      background: "dark",
      primaryAccent: "blue",
      aiCoreColor: "cyan",
      agentGlow: "global",
      glassIntensity: "balanced",
      borderIntensity: "standard",
      motion: "cinematic",
      backgroundEffect: "particles",
      density: "comfortable",
      timeAwareAuto: false,
    },
    previewColors: { bg: "#05070B", surface: "#111318", accent: "#2E7BFF", aiCore: "#00E5FF" },
  },
  aurora: {
    name: "Aurora",
    tagline: "Cinematic Atmosphere",
    description: "Deep cosmic violet backdrop with ethereal teal glow and rich spatial depth.",
    badge: "Atmospheric",
    config: {
      preset: "aurora",
      background: "dark",
      primaryAccent: "violet",
      aiCoreColor: "teal",
      agentGlow: "global",
      glassIntensity: "strong",
      borderIntensity: "standard",
      motion: "immersive",
      backgroundEffect: "aurora",
      density: "comfortable",
      timeAwareAuto: false,
    },
    previewColors: { bg: "#090A15", surface: "#131424", accent: "#8B5CF6", aiCore: "#14B8A6" },
  },
  arctic: {
    name: "Arctic",
    tagline: "Crisp High-Key Light",
    description: "Bright cool white surfaces with electric blue accents and subtle clean glass.",
    badge: "Light Mode",
    config: {
      preset: "arctic",
      background: "light",
      primaryAccent: "blue",
      aiCoreColor: "cyan",
      agentGlow: "monochrome",
      glassIntensity: "minimal",
      borderIntensity: "standard",
      motion: "subtle",
      backgroundEffect: "grid",
      density: "comfortable",
      timeAwareAuto: false,
    },
    previewColors: { bg: "#F8FAFC", surface: "#FFFFFF", accent: "#0284C7", aiCore: "#0EA5E9" },
  },
  paper: {
    name: "Paper",
    tagline: "Warm Editorial Calm",
    description: "Warm cream surfaces, soft dark typography, and calm amber accents for reading.",
    badge: "Editorial",
    config: {
      preset: "paper",
      background: "warm",
      primaryAccent: "amber",
      aiCoreColor: "rose",
      agentGlow: "off",
      glassIntensity: "minimal",
      borderIntensity: "subtle",
      motion: "subtle",
      backgroundEffect: "none",
      density: "comfortable",
      timeAwareAuto: false,
    },
    previewColors: { bg: "#FDFBF7", surface: "#F7F4EB", accent: "#D97706", aiCore: "#F43F5E" },
  },
  midnight: {
    name: "Midnight",
    tagline: "True OLED Black",
    description: "True pitch-black OLED surfaces with low brightness and zero visual glare.",
    badge: "OLED Friendly",
    config: {
      preset: "midnight",
      background: "dark",
      customBackgroundHex: "#000000",
      primaryAccent: "cyan",
      aiCoreColor: "blue",
      agentGlow: "monochrome",
      glassIntensity: "minimal",
      borderIntensity: "subtle",
      motion: "subtle",
      backgroundEffect: "none",
      density: "comfortable",
      timeAwareAuto: false,
    },
    previewColors: { bg: "#000000", surface: "#0A0A0C", accent: "#06B6D4", aiCore: "#3B82F6" },
  },
  focus: {
    name: "Focus",
    tagline: "Zero Distraction",
    description: "High readability slate theme with compact density and disabled decorative animations.",
    badge: "Productivity",
    config: {
      preset: "focus",
      background: "dark",
      primaryAccent: "emerald",
      aiCoreColor: "emerald",
      agentGlow: "off",
      glassIntensity: "minimal",
      borderIntensity: "standard",
      motion: "off",
      backgroundEffect: "none",
      density: "compact",
      timeAwareAuto: false,
    },
    previewColors: { bg: "#0F172A", surface: "#1E293B", accent: "#10B981", aiCore: "#10B981" },
  },
  custom: {
    name: "Custom",
    tagline: "User Personalized",
    description: "Completely customizable colors, glassmorphism, density, and animation speed.",
    badge: "Studio",
    config: {
      preset: "custom",
      background: "dark",
      primaryAccent: "violet",
      aiCoreColor: "cyan",
      agentGlow: "global",
      glassIntensity: "balanced",
      borderIntensity: "standard",
      motion: "cinematic",
      backgroundEffect: "ambient_glow",
      density: "comfortable",
      timeAwareAuto: false,
    },
    previewColors: { bg: "#05070B", surface: "#111318", accent: "#8B5CF6", aiCore: "#06B6D4" },
  },
};

export const INITIAL_SAVED_THEMES: SavedCustomTheme[] = [
  {
    id: "slot-1",
    name: "Cyber Neon Studio",
    config: {
      preset: "custom",
      background: "dark",
      primaryAccent: "rose",
      aiCoreColor: "cyan",
      agentGlow: "global",
      glassIntensity: "strong",
      borderIntensity: "strong",
      motion: "immersive",
      backgroundEffect: "aurora",
      density: "comfortable",
      timeAwareAuto: false,
    },
    createdAt: Date.now() - 86400000 * 2,
    updatedAt: Date.now() - 86400000 * 2,
  },
  {
    id: "slot-2",
    name: "Emerald Executive",
    config: {
      preset: "custom",
      background: "dark",
      primaryAccent: "emerald",
      aiCoreColor: "emerald",
      agentGlow: "monochrome",
      glassIntensity: "balanced",
      borderIntensity: "standard",
      motion: "subtle",
      backgroundEffect: "grid",
      density: "compact",
      timeAwareAuto: false,
    },
    createdAt: Date.now() - 86400000,
    updatedAt: Date.now() - 86400000,
  },
  {
    id: "slot-3",
    name: "Minimal Parchment",
    config: {
      preset: "custom",
      background: "warm",
      primaryAccent: "amber",
      aiCoreColor: "rose",
      agentGlow: "off",
      glassIntensity: "minimal",
      borderIntensity: "subtle",
      motion: "off",
      backgroundEffect: "none",
      density: "comfortable",
      timeAwareAuto: false,
    },
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
];
